<?php
$title = 'Add new account';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('account', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formRow($form->get('accountname')) . PHP_EOL;
echo $this->formRow($form->get('accpass')) . PHP_EOL;
echo $this->formRow($form->get('address')) . PHP_EOL;
echo $this->formRow($form->get('sexual')) . PHP_EOL;
echo $this->formRow($form->get('email')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

