<?php
$title = 'My album';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'artist')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>
<?php 
// echo 'hang si '.WEB_PATH_IMG;
// echo '<br/>';
?>
<img src="<?php echo WEB_PATH_IMG;?>/book1/car_magazine_1.jpg" style="width: 50px;height:40px;">

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php
echo $this->url('album', array(
    'action' => 'add'));
?>">Add new album</a></p>


<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('album', array('order_by' => 'title', 'order' => $url_order)); ?>">Title Name <?php if ($order_by == 'title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('album', array('order_by' => 'artist', 'order' => $url_order)); ?>">Artist <?php if ($order_by == 'artist'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>     
        <th><a href="#">Action</a></th>
    </tr>
    <?php foreach ($paginatoralbum as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title); ?></td>
            <td><?php echo $this->escapeHtml($album->artist); ?></td>
            <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
    echo $this->paginationControl(
            $paginatoralbum, 'Sliding', 'paginator-album', array('order_by' => $order_by, 'order' => $order)
    );
    ?>